/**
 * Workflow Assignments List Page
 *
 * Which workflow runs on which collection: search, pagination, and
 * permission-gated create/edit/delete. A row opens the assignment form.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { WorkflowAssignmentsManager } from '@/components/ui/workflow-management';

export default function WorkflowAssignmentsPage() {
  const router = useLocaleRouter();

  return (
    <WorkflowAssignmentsManager
      onAssignmentClick={(assignment) => router.push(`/workflow-assignments/${assignment.id}`)}
      onCreateAssignment={() => router.push('/workflow-assignments/new')}
    />
  );
}
