/**
 * Workflow Instance Detail Page
 *
 * One workflow instance (read-only): its item, current state, the state
 * diagram, and the transition history.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { WorkflowInstanceDetail } from '@/components/ui/workflow-management';

export default function WorkflowInstanceDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useLocaleRouter();

  return <WorkflowInstanceDetail id={id} onBack={() => router.push('/workflow-instances')} />;
}
