/**
 * @buildpad/utils
 * 
 * Utility functions for Buildpad UI packages.
 * Includes field interface mapping, value formatting, and validation helpers.
 */

// Field Interface Mapper
export {
  getFieldInterface,
  getFieldDefault,
  getFieldValidation,
  formatFieldValue,
  isFieldReadOnly,
  isUUIDAutoGenerated,
  hasAutoGeneratedDefault,
  getAutoGenerationType,
  isPresentationField,
  type InterfaceType,
  type InterfaceConfig,
  type FieldReadOnlyOptions,
} from './field-interface-mapper';

// Interface Types
export type {
  FieldType,
  LocalType,
  InterfaceGroup,
  InterfaceProps,
  InterfaceOption,
  InterfaceOptionMeta,
  InterfaceDefinition,
  InterfaceMetadata,
  InterfaceRegistrationInput,
  InterfaceGroupDefinition,
} from './interface-types';

// Interface Registry
export {
  InterfaceRegistry,
  interfaceRegistry,
  getInterfaceRegistry,
} from './interface-registry';

// Define Interface Helper
export {
  defineInterface,
  defineInterfaces,
  createInterfaceOption,
  createOptionGroup,
  InterfaceOptions,
  type DefineInterfaceConfig,
} from './define-interface';

// Load Interfaces from Registry
export {
  loadInterfacesFromRegistry,
  extractInterfaceFromComponent,
  getInterfacesForApi,
  type RegistryComponent,
  type RegistryComponentInterface,
  type RegistryJson,
} from './load-interfaces';

// New Item Detection
export { isNewItem, isExistingItem } from './is-new-item';

// Field Translation / Display Name
export { getFieldDisplayName, formatFieldTitle } from './translate-field';

// Form definition overlay merge (Dynamic Form Builder)
export {
  buildFieldsFromDefinition,
  MISSING_FIELD_MARKER,
} from './build-fields-from-definition';

// Field/Collection provisioning spec → DaaS payload mapper (DDL)
export {
  fieldSpecToDaaSField,
  dataTypeForFieldType,
  interfaceForFieldType,
  type DaaSFieldPayload,
} from './field-spec-mapper';

// Provisionable interface catalog (type-aware picker for the form builder)
export {
  PROVISIONABLE_INTERFACES,
  provisionableInterfacesForType,
  type ProvisionableInterface,
  type ProvisionableInterfaceGroup,
} from './interface-catalog';
