/**
 * @buildpad/utils
 * 
 * Utility functions for Buildpad UI packages.
 * Includes field interface mapping, value formatting, and validation helpers.
 */

// Concealed values (hash / conceal specials)
export {
  CONCEALED_PLACEHOLDER,
  isConcealedValue,
  isConcealedField,
  concealingInterface,
} from './conceal';

// Field Interface Mapper
export {
  getFieldInterface,
  getFieldDefault,
  getDefaultValuesFromFields,
  getFieldValidation,
  formatFieldValue,
  isFieldReadOnly,
  isUUIDAutoGenerated,
  hasAutoGeneratedDefault,
  getAutoGenerationType,
  isPresentationField,
  type InterfaceType,
  type InterfaceConfig,
  type FieldReadOnlyOptions,
} from './field-interface-mapper';

// Interface Types
export type {
  FieldType,
  LocalType,
  InterfaceGroup,
  InterfaceProps,
  InterfaceOption,
  InterfaceOptionMeta,
  InterfaceDefinition,
  InterfaceMetadata,
  InterfaceRegistrationInput,
  InterfaceGroupDefinition,
} from './interface-types';

// Interface Registry
export {
  InterfaceRegistry,
  interfaceRegistry,
  getInterfaceRegistry,
} from './interface-registry';

// Define Interface Helper
export {
  defineInterface,
  defineInterfaces,
  createInterfaceOption,
  createOptionGroup,
  InterfaceOptions,
  type DefineInterfaceConfig,
} from './define-interface';

// Load Interfaces from Registry
export {
  loadInterfacesFromRegistry,
  extractInterfaceFromComponent,
  getInterfacesForApi,
  type RegistryComponent,
  type RegistryComponentInterface,
  type RegistryJson,
} from './load-interfaces';

// New Item Detection
export { isNewItem, isExistingItem } from './is-new-item';

// Field Translation / Display Name
export { getFieldDisplayName, formatFieldTitle } from './translate-field';

// Form definition overlay merge (Dynamic Form Builder)
export {
  buildFieldsFromDefinition,
  MISSING_FIELD_MARKER,
} from './build-fields-from-definition';

// Field/Collection provisioning spec → DaaS payload mapper (DDL)
export {
  fieldSpecToDaaSField,
  dataTypeForFieldType,
  interfaceForFieldType,
  type DaaSFieldPayload,
} from './field-spec-mapper';

// Provisionable interface catalog (type-aware picker for the form builder)
export {
  PROVISIONABLE_INTERFACES,
  provisionableInterfacesForType,
  CHOICE_INTERFACES,
  interfaceRequiresChoices,
  resolveChoiceLabel,
  parseChoiceValues,
  splitCsvValue,
  type InterfaceChoice,
  type ProvisionableInterface,
  type ProvisionableInterfaceGroup,
} from './interface-catalog';

// Component i18n core: dictionary shape, English defaults, bundled locales,
// merge / interpolate / plural helpers. The React provider and hooks live in
// @buildpad/services (re-exported by @buildpad/hooks).
export {
  defaultTranslations,
  en,
  id,
  bundledLocales,
  bundledTranslationsFor,
  mergeTranslations,
  interpolate,
  hasPlaceholders,
  pluralCategory,
  selectPlural,
  formatCount,
  DEFAULT_LOCALE,
  languageOf,
  directionForLocale,
  lookupTranslation,
  translate,
  type BuildpadTranslations,
  type BuildpadTranslationsInput,
  type CommonTranslations,
  type DeepPartial,
  type FormTranslations,
  type FormValidationTranslations,
  type InterfacesTranslations,
  type InterpolationValues,
  type ListM2MTranslations,
  type PluralForms,
  type TableTranslations,
  type TextDirection,
} from './i18n';
