/**
 * Edit Form Page
 *
 * Loads an existing form definition into <FormBuilder/> for editing. The
 * target collection is taken from the saved definition.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { use } from 'react';
import Link from 'next/link';
import { useLocaleHref, useLocaleRouter } from '@/lib/i18n/navigation';
import { useI18n } from '@/lib/i18n/provider';
import { Anchor, Breadcrumbs, Button, Group, Stack, Text } from '@mantine/core';
import { IconPlayerPlay } from '@tabler/icons-react';
import { FormBuilder } from '@/components/ui/form-builder';

export default function EditFormPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useLocaleRouter();
  const href = useLocaleHref();
  const { t } = useI18n();

  return (
    <Stack gap="md">
      <Group justify="space-between">
        <Breadcrumbs>
          <Anchor component={Link} href={href('/forms')} size="sm">
            {t('app.forms.title')}
          </Anchor>
          <Text size="sm">{t('app.forms.editForm')}</Text>
        </Breadcrumbs>
        <Button
          variant="light"
          leftSection={<IconPlayerPlay size={16} />}
          onClick={() => router.push(`/forms/${id}/fill`)}
        >
          {t('app.forms.fillOut')}
        </Button>
      </Group>
      <FormBuilder definitionId={id} />
    </Stack>
  );
}
