/**
 * Edit Form Screen Page
 *
 * Loads an existing form definition into <FormBuilder/> for editing. The target
 * collection is taken from the saved definition.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { use } from 'react';
import { useRouter } from 'next/navigation';
import { Button, Group, Stack } from '@mantine/core';
import { IconPlayerPlay } from '@tabler/icons-react';
import { FormBuilder } from '@/components/ui/form-builder';

export default function EditFormPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();

  return (
    <Stack gap="md">
      <Group justify="flex-end">
        <Button
          variant="light"
          leftSection={<IconPlayerPlay size={16} />}
          onClick={() => router.push(`/forms/${id}/fill`)}
        >
          Fill
        </Button>
      </Group>
      <FormBuilder definitionId={id} />
    </Stack>
  );
}
