/**
 * File Detail Page
 *
 * Preview tab (image/video/audio/pdf) and an editable metadata form
 * (title, description, tags, location, download filename) for a single file.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useRouter } from 'next/navigation';
import { FileDetail } from '@/components/ui/file-manager';

export default function FileDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();

  return (
    <FileDetail
      id={id}
      onBack={() => router.push('/files')}
      onDeleted={() => router.push('/files')}
    />
  );
}
