/**
 * Buildpad Utils
 * 
 * Re-exports all utility functions.
 * This file is copied to your project and can be customized.
 */

// Basic utilities
export { cn, formatFileSize, getFileCategory, getAssetUrl, slugify, slugify as generateSlug, debounce, isValidPrimaryKey, deepMerge, generateId } from '../common-utils';

// New item detection
export { isNewItem, isExistingItem } from '../is-new-item';

// Concealed values (hash / conceal specials)
export {
  CONCEALED_PLACEHOLDER,
  isConcealedValue,
  isConcealedField,
  concealingInterface,
} from '../conceal';

// Form definition overlay merge (drives the dynamic form builder runtime)
export { buildFieldsFromDefinition, MISSING_FIELD_MARKER } from '../build-fields-from-definition';

// Field/Collection provisioning spec → DaaS payload mapper (DDL)
export {
  fieldSpecToDaaSField,
  dataTypeForFieldType,
  interfaceForFieldType,
  type DaaSFieldPayload,
} from '../field-spec-mapper';

// Provisionable interface catalog (type-aware picker for the form builder)
export {
  PROVISIONABLE_INTERFACES,
  provisionableInterfacesForType,
  CHOICE_INTERFACES,
  interfaceRequiresChoices,
  resolveChoiceLabel,
  parseChoiceValues,
  splitCsvValue,
  type ProvisionableInterface,
  type ProvisionableInterfaceGroup,
  type InterfaceChoice,
} from '../interface-catalog';

// Field interface mapping (from @buildpad/utils)
export { 
  getFieldInterface,
  getFieldDefault,
  getFieldDisplayName,
  formatFieldTitle,
  type InterfaceType,
  type InterfaceConfig,
} from '../field-interface-mapper';

// Field utilities
export {
  isFieldReadOnly,
  isPresentationField,
  getFieldValidation,
  formatFieldValue,
  getDefaultValuesFromFields,
  isUUIDAutoGenerated,
  hasAutoGeneratedDefault,
  getAutoGenerationType,
  type FieldReadOnlyOptions,
} from '../field-interface-mapper';

// Interface type definitions
export type {
  InterfaceDefinition,
  InterfaceGroup,
} from '../interface-types';

// Interface type definitions (the remaining public types)
export type {
  FieldType,
  LocalType,
  InterfaceProps,
  InterfaceOption,
  InterfaceOptionMeta,
  InterfaceMetadata,
  InterfaceRegistrationInput,
  InterfaceGroupDefinition,
} from '../interface-types';

// Interface registry — shipped as lib/buildpad/interface-registry.ts
export {
  InterfaceRegistry,
  interfaceRegistry,
  getInterfaceRegistry,
} from '../interface-registry';

// Define-interface helpers — shipped as lib/buildpad/define-interface.ts
export {
  defineInterface,
  defineInterfaces,
  createInterfaceOption,
  createOptionGroup,
  InterfaceOptions,
  type DefineInterfaceConfig,
} from '../define-interface';

// Component i18n core — dictionary shape, English defaults, bundled locales,
// merge / interpolate / plural helpers (shipped as lib/buildpad/i18n/*).
// The provider + hooks live in lib/buildpad/services and lib/buildpad/hooks.
export {
  defaultTranslations,
  en,
  id,
  bundledLocales,
  bundledTranslationsFor,
  mergeTranslations,
  interpolate,
  hasPlaceholders,
  pluralCategory,
  selectPlural,
  formatCount,
  DEFAULT_LOCALE,
  languageOf,
  directionForLocale,
  lookupTranslation,
  translate,
  type BuildpadTranslations,
  type BuildpadTranslationsInput,
  type CommonTranslations,
  type CollectionsTranslations,
  type FilesTranslations,
  type UsersTranslations,
  type FormsTranslations,
  type HooksTranslations,
  type DateTimeTranslations,
  type DeepPartial,
  type FormTranslations,
  type FormValidationTranslations,
  type InterfacesTranslations,
  type InterpolationValues,
  type ListM2MTranslations,
  type PluralForms,
  type TableTranslations,
  type TextDirection,
} from '../i18n';
