/**
 * Collection List Page
 *
 * Displays a table of items for the given collection with search,
 * filtering, pagination, selection, and bulk actions.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use, useEffect } from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { useI18n } from '@/lib/i18n/provider';
import { IconTrash } from '@tabler/icons-react';
import { CollectionList } from '@/components/ui/collection-list';
import { useLocalStorage } from '@/lib/buildpad/hooks';
import type { BulkAction } from '@/components/ui/collection-list';

export default function CollectionPage({
  params,
}: {
  params: Promise<{ collection: string }>;
}) {
  const { collection } = use(params);
  const router = useLocaleRouter();
  const { t } = useI18n();
  const { setValue: setLastAccessed } = useLocalStorage<string>('last-accessed-collection');

  // Track last accessed collection
  useEffect(() => {
    setLastAccessed(collection);
  }, [collection, setLastAccessed]);

  const bulkActions: BulkAction[] = [
    {
      label: t('app.common.delete'),
      icon: <IconTrash size={16} />,
      color: 'red',
      action: async (selectedIds) => {
        if (!confirm(t('app.content.deleteConfirm', { count: selectedIds.length }))) return;
        try {
          await fetch(`/api/items/${collection}`, {
            method: 'DELETE',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(selectedIds),
          });
          // CollectionList will auto-refresh
          window.location.reload();
        } catch (error) {
          console.error('Batch delete failed:', error);
        }
      },
    },
  ];

  return (
    <CollectionList
      collection={collection}
      enableSearch
      enableSelection
      bulkActions={bulkActions}
      onItemClick={(item) => router.push(`/content/${collection}/${item.id}`)}
    />
  );
}
