/**
 * Policy Detail Page
 *
 * Create/edit a policy: basic info, access flags (app/admin/delegate), and
 * the per-collection permissions matrix. Use the `/policies/new` route to
 * create; the matrix appears once the policy exists.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useRouter } from 'next/navigation';
import { PolicyDetail } from '@/components/ui/users-management';

export default function PolicyDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();

  return (
    <PolicyDetail
      id={id}
      onBack={() => router.push('/policies')}
      onDeleted={() => router.push('/policies')}
      onSaved={(policy) => {
        // After create, go to the saved policy so the permissions matrix appears.
        if (id === 'new') router.replace(`/policies/${policy.id}`);
      }}
    />
  );
}
