/**
 * Policy Detail Page
 *
 * Create/edit a policy: basic info, access flags (app/admin/delegate), and
 * the per-collection permissions matrix. Use the `/policies/new` route to
 * create; the matrix appears once the policy exists.
 *
 * The form does not navigate. After a create it goes on as the editor of the
 * policy that was stored, and this page replaces the URL with that policy's.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { PolicyDetail } from '@/components/ui/users-management';

export default function PolicyDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useLocaleRouter();

  return (
    <PolicyDetail
      id={id}
      onBack={() => router.push('/policies')}
      onDeleted={() => router.push('/policies')}
      onSaved={(policy) => {
        // After a create the form goes on as the editor of the stored policy,
        // with its permissions matrix. Go to its route so the URL names it.
        if (id === 'new') router.replace(`/policies/${policy.id}`);
      }}
    />
  );
}
