/**
 * Files List Page
 *
 * Full file-management surface: drag-and-drop upload, import-from-URL,
 * folder navigation, grid/list views, search, and bulk delete.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useRouter } from 'next/navigation';
import { FileManager } from '@/components/ui/file-manager';

export default function FilesPage() {
  const router = useRouter();

  return <FileManager onFileClick={(file) => router.push(`/files/${file.id}`)} />;
}
