/**
 * Workflow Instances List Page
 *
 * The workflows running on items (read-only): search and pagination. A row
 * opens the instance with its transition history.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { WorkflowInstancesManager } from '@/components/ui/workflow-management';

export default function WorkflowInstancesPage() {
  const router = useLocaleRouter();

  return (
    <WorkflowInstancesManager
      onInstanceClick={(instance) => router.push(`/workflow-instances/${instance.id}`)}
    />
  );
}
