/**
 * New Form Screen Page
 *
 * Pick how the screen's target collection comes to be, then build it with
 * <FormBuilder/>:
 *   - **Start building** (default, needs DaaS schema rights) — the target
 *     collection is optional up front. Build the screen right away; on save the
 *     builder auto-creates a brand-new, `fb_`-prefixed collection from the screen
 *     name (full storage: standard system fields + every field a real, searchable
 *     column, no `extras` tail).
 *   - **Use existing collection** — bind to a collection you already have
 *     (hybrid storage: real columns + an opt-in `extras` jsonb tail). The only
 *     path when you lack schema rights.
 *
 * On save the user is redirected to the screen's edit page.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  Anchor,
  Button,
  Group,
  Stack,
  Text,
  TextInput,
  Title,
} from '@mantine/core';
import { IconArrowRight, IconDatabasePlus } from '@tabler/icons-react';
import { FormBuilder } from '@/components/ui/form-builder';
import { usePermissions } from '@/lib/buildpad/hooks';

/** How the screen was started: bound to an existing collection, or auto-create. */
type Start = { mode: 'auto' } | { mode: 'existing'; collection: string };

export default function NewFormPage() {
  const router = useRouter();
  const { isAdmin } = usePermissions();

  // Auto-creating a collection needs DaaS schema rights; non-admins can only
  // bind to an existing collection.
  const canCreate = isAdmin;

  const [bindExisting, setBindExisting] = useState(!canCreate);
  const [collectionInput, setCollectionInput] = useState('');
  const [start, setStart] = useState<Start | null>(null);

  // Once started, hand off to the builder. In `auto` mode no target collection
  // is passed — the builder provisions an `fb_` full collection on first save.
  if (start) {
    return (
      <FormBuilder
        targetCollection={start.mode === 'existing' ? start.collection : undefined}
        onSaved={(def) => router.push(`/forms/${def.id}`)}
      />
    );
  }

  return (
    <Stack gap="md" maw={520}>
      <Title order={3}>New screen</Title>

      {!bindExisting ? (
        <>
          <Text size="sm" c="dimmed">
            Start building right away — no collection needed up front. When you
            save, a new <b>fb_</b>-prefixed collection is created from the screen
            name, with standard system fields and every field as a real,
            searchable column (no <b>extras</b> tail).
          </Text>
          <Group>
            <Button
              leftSection={<IconDatabasePlus size={16} />}
              onClick={() => setStart({ mode: 'auto' })}
            >
              Start building
            </Button>
          </Group>
          <Anchor
            component="button"
            type="button"
            size="sm"
            onClick={() => setBindExisting(true)}
          >
            or bind to an existing collection
          </Anchor>
        </>
      ) : (
        <>
          <TextInput
            label="Target collection"
            description="Bind this screen to a collection you already have (hybrid storage: real columns + an opt-in extras jsonb tail)."
            placeholder="e.g. issues"
            value={collectionInput}
            onChange={(e) => setCollectionInput(e.currentTarget.value)}
          />
          <Group>
            <Button
              rightSection={<IconArrowRight size={16} />}
              disabled={!collectionInput.trim()}
              onClick={() =>
                setStart({ mode: 'existing', collection: collectionInput.trim() })
              }
            >
              Start building
            </Button>
          </Group>
          {canCreate && (
            <Anchor
              component="button"
              type="button"
              size="sm"
              onClick={() => setBindExisting(false)}
            >
              or create a new collection automatically
            </Anchor>
          )}
        </>
      )}
    </Stack>
  );
}
