/**
 * New Form Page
 *
 * Pick where the form's responses will be stored, then build it with
 * <FormBuilder/>:
 *   - **Start from scratch** (default, needs DaaS schema rights) — no
 *     collection needed up front. On save the builder auto-creates a
 *     brand-new, `fb_`-prefixed collection from the form name (full storage:
 *     standard system fields + every field a real, searchable column, no
 *     `extras` tail).
 *   - **Use an existing collection** — bind to a collection you already have
 *     (hybrid storage: real columns + an opt-in `extras` jsonb tail). The
 *     only path when you lack schema rights.
 *
 * On save the user is redirected to the form's edit page.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useLocaleHref, useLocaleRouter } from '@/lib/i18n/navigation';
import { useI18n } from '@/lib/i18n/provider';
import {
  Anchor,
  Breadcrumbs,
  Button,
  Card,
  Group,
  Loader,
  Radio,
  Stack,
  Text,
  TextInput,
  ThemeIcon,
  Title,
} from '@mantine/core';
import { IconDatabase, IconDatabasePlus } from '@tabler/icons-react';
import { FormBuilder } from '@/components/ui/form-builder';
import { useDaaSContext } from '@/lib/buildpad/hooks';

/** How the form was started: bound to an existing collection, or auto-create. */
type Start = { mode: 'auto' } | { mode: 'existing'; collection: string };

type Choice = 'scratch' | 'existing';

function ChoiceCard({
  selected,
  onSelect,
  icon,
  title,
  description,
  hint,
  children,
}: {
  selected: boolean;
  onSelect: () => void;
  icon: React.ReactNode;
  title: string;
  description: string;
  hint: string;
  children?: React.ReactNode;
}) {
  return (
    <Card
      withBorder
      radius="md"
      padding="md"
      onClick={onSelect}
      style={{
        cursor: 'pointer',
        borderColor: selected ? 'var(--mantine-primary-color-filled)' : undefined,
      }}
    >
      <Group align="flex-start" wrap="nowrap" gap="sm">
        <Radio checked={selected} onChange={onSelect} mt={2} aria-label={title} />
        <ThemeIcon variant="light" size={36} radius="md">
          {icon}
        </ThemeIcon>
        <Stack gap={4} style={{ flex: 1, minWidth: 0 }}>
          <Text fw={600}>{title}</Text>
          <Text size="sm">{description}</Text>
          <Text size="xs" c="dimmed">
            {hint}
          </Text>
          {selected && children}
        </Stack>
      </Group>
    </Card>
  );
}

export default function NewFormPage() {
  const router = useLocaleRouter();
  const href = useLocaleHref();
  const { t } = useI18n();
  // Read admin/schema rights from the DaaS context, which resolves the dynamic
  // Supabase token (via `getToken`). See useDaaSContext for why this is the
  // reliable source with dynamic auth.
  const { isAdmin, authLoading: permsLoading } = useDaaSContext();

  // Auto-creating a collection needs DaaS schema rights; non-admins can only
  // bind to an existing collection.
  const canCreate = isAdmin;

  // `null` = follow the permission-derived default; a value = the user
  // explicitly picked a path. Do NOT seed this from `canCreate` via a
  // useState initializer: auth resolves asynchronously (`isAdmin` is false on
  // the first render, then flips true once the DaaS user loads), and a
  // useState initializer runs only once.
  const [choiceOverride, setChoiceOverride] = useState<Choice | null>(null);
  const choice: Choice = choiceOverride ?? (canCreate ? 'scratch' : 'existing');
  const [collectionInput, setCollectionInput] = useState('');
  const [start, setStart] = useState<Start | null>(null);

  const breadcrumbs = (
    <Breadcrumbs>
      <Anchor component={Link} href={href('/forms')} size="sm">
        {t('app.forms.title')}
      </Anchor>
      <Text size="sm">{t('app.forms.newForm')}</Text>
    </Breadcrumbs>
  );

  // Wait for permissions before choosing a default path, so admins aren't
  // shown the "existing collection" default during the brief pre-token window.
  if (permsLoading) {
    return (
      <Stack gap="md" maw={560}>
        {breadcrumbs}
        <Title order={3}>{t('app.forms.newForm')}</Title>
        <Group gap="xs">
          <Loader size="xs" />
          <Text size="sm" c="dimmed">
            {t('app.forms.checkingPermissions')}
          </Text>
        </Group>
      </Stack>
    );
  }

  // Once started, hand off to the builder. In `auto` mode no target collection
  // is passed — the builder provisions an `fb_` full collection on first save.
  if (start) {
    return (
      <Stack gap="md">
        {breadcrumbs}
        <FormBuilder
          targetCollection={start.mode === 'existing' ? start.collection : undefined}
          onSaved={(def) => router.push(`/forms/${def.id}`)}
        />
      </Stack>
    );
  }

  const canStart =
    choice === 'scratch' ? canCreate : collectionInput.trim().length > 0;

  return (
    <Stack gap="md" maw={560}>
      {breadcrumbs}
      <div>
        <Title order={3}>{t('app.forms.newForm')}</Title>
        <Text size="sm" c="dimmed">
          {t('app.forms.chooseStorage')}
        </Text>
      </div>

      {canCreate && (
        <ChoiceCard
          selected={choice === 'scratch'}
          onSelect={() => setChoiceOverride('scratch')}
          icon={<IconDatabasePlus size={20} />}
          title={t('app.forms.scratchTitle')}
          description={t('app.forms.scratchDescription')}
          hint={t('app.forms.scratchHint')}
        />
      )}

      <ChoiceCard
        selected={choice === 'existing'}
        onSelect={() => setChoiceOverride('existing')}
        icon={<IconDatabase size={20} />}
        title={t('app.forms.existingTitle')}
        description={t('app.forms.existingDescription')}
        hint={t('app.forms.existingHint')}
      >
        <TextInput
          mt={4}
          placeholder={t('app.forms.targetCollectionPlaceholder')}
          aria-label={t('app.forms.targetCollection')}
          value={collectionInput}
          onChange={(e) => setCollectionInput(e.currentTarget.value)}
          onClick={(e) => e.stopPropagation()}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && collectionInput.trim()) {
              setStart({ mode: 'existing', collection: collectionInput.trim() });
            }
          }}
        />
      </ChoiceCard>

      <Group>
        <Button
          disabled={!canStart}
          onClick={() =>
            setStart(
              choice === 'scratch'
                ? { mode: 'auto' }
                : { mode: 'existing', collection: collectionInput.trim() }
            )
          }
        >
          {t('app.forms.startBuilding')}
        </Button>
      </Group>
    </Stack>
  );
}
