/**
 * Cron Job Detail Page
 *
 * Create/edit a cron job: its code beside its settings (name, description,
 * schedule, timezone, timeout, memory limit, status), Run Now and Activate
 * or Deactivate, and the job's run history on a second tab. Use the
 * `/cron/new` route to create.
 *
 * The editor does not navigate. After a create it still holds `id="new"`,
 * so this page opens the editor of the job that was stored; after a save of
 * an existing job it stays where it is.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { CronJobDetail } from '@/components/ui/cron-management';

export default function CronJobDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useLocaleRouter();

  return (
    <CronJobDetail
      id={id}
      onBack={() => router.push('/cron')}
      onCreated={(job) => router.push(`/cron/${job.id}`)}
    />
  );
}
