/**
 * Content Module Layout
 *
 * Provides a content management shell with sidebar collection navigation,
 * header bar, and main content area. Wraps all /content/* pages.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { usePathname } from 'next/navigation';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { useI18n } from '@/lib/i18n/provider';
import { stripLocale } from '@/lib/i18n/config';
import { ContentLayout } from '@/components/ui/content-layout';
import { ContentNavigation } from '@/components/ui/content-navigation';
import { useCollections } from '@/lib/buildpad/hooks';

export default function ContentModuleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useLocaleRouter();
  const { t } = useI18n();
  const pathname = usePathname();

  // Extract current collection from URL: /[lang]/content/[collection]/...
  const segments = stripLocale(pathname).split('/');
  const currentCollection = segments.length > 2 ? segments[2] : undefined;

  const {
    rootCollections,
    activeGroups,
    toggleGroup,
    showHidden,
    setShowHidden,
    hasHiddenCollections,
    showSearch,
    dense,
    loading,
  } = useCollections({ currentCollection });

  return (
    <ContentLayout
      breadcrumbs={[{ label: t('app.content.breadcrumb'), href: router.href('/content') }]}
      sidebar={
        <ContentNavigation
          rootCollections={rootCollections}
          activeGroups={activeGroups}
          onToggleGroup={toggleGroup}
          currentCollection={currentCollection}
          onNavigate={(collection) => router.push(`/content/${collection}`)}
          showHidden={showHidden}
          onToggleHidden={() => setShowHidden(!showHidden)}
          hasHiddenCollections={hasHiddenCollections}
          showSearch={showSearch}
          dense={dense}
          loading={loading}
        />
      }
    >
      {children}
    </ContentLayout>
  );
}
