/**
 * Content Module Index Page
 *
 * Redirects to the first available collection, or shows an empty state
 * if there are no collections yet.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { useEffect } from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { useI18n } from '@/lib/i18n/provider';
import { Stack, Text, Center } from '@mantine/core';
import { IconBox } from '@tabler/icons-react';
import { useCollections } from '@/lib/buildpad/hooks';
import { useLocalStorage } from '@/lib/buildpad/hooks';

export default function ContentIndexPage() {
  const router = useLocaleRouter();
  const { t } = useI18n();
  const { visibleCollections, loading } = useCollections();
  const { value: lastAccessed } = useLocalStorage<string>('last-accessed-collection');

  useEffect(() => {
    if (loading) return;

    // Redirect to last accessed collection if it still exists
    if (lastAccessed) {
      const exists = visibleCollections.find((c) => c.collection === lastAccessed);
      if (exists) {
        router.replace(`/content/${lastAccessed}`);
        return;
      }
    }

    // Redirect to first available collection
    if (visibleCollections.length > 0) {
      const first = visibleCollections.find((c) => !!c.schema);
      if (first) {
        router.replace(`/content/${first.collection}`);
        return;
      }
    }
  }, [loading, lastAccessed, visibleCollections, router]);

  if (loading) return null;

  // No collections — show empty state
  if (visibleCollections.length === 0) {
    return (
      <Center style={{ minHeight: '60vh' }}>
        <Stack align="center" gap="md">
          <IconBox size={64} color="var(--mantine-color-gray-5)" stroke={1.5} />
          <Text size="xl" fw={600}>
            {t('app.content.noCollections')}
          </Text>
          <Text c="dimmed" ta="center" maw={400}>
            {t('app.content.noCollectionsHint')}
          </Text>
        </Stack>
      </Center>
    );
  }

  return null;
}
