/**
 * Users List Page
 *
 * Users administration surface: search, role/status filters, pagination,
 * and permission-gated create/edit/delete.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { UsersManager } from '@/components/ui/users-management';

export default function UsersPage() {
  const router = useLocaleRouter();

  return (
    <UsersManager
      onUserClick={(user) => router.push(`/users/${user.id}`)}
      onCreateUser={() => router.push('/users/new')}
    />
  );
}
