/**
 * Cron Jobs List Page
 *
 * Cron jobs: search, pagination, and permission-gated row actions (edit,
 * run now, activate or deactivate, clone, delete), with the run history of
 * every job on a second tab. A row opens the job editor.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { CronJobsManager } from '@/components/ui/cron-management';

export default function CronJobsPage() {
  const router = useLocaleRouter();

  return (
    <CronJobsManager
      onJobClick={(job) => router.push(`/cron/${job.id}`)}
      onCreateJob={() => router.push('/cron/new')}
    />
  );
}
