/**
 * Role Detail Page
 *
 * Create/edit a role: name, icon, description, parent role (hierarchy),
 * scope-assignment rules, member management, and policy attachment. Use the
 * `/roles/new` route to create.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useRouter } from 'next/navigation';
import { RoleDetail } from '@/components/ui/users-management';

export default function RoleDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();

  return (
    <RoleDetail
      id={id}
      onBack={() => router.push('/roles')}
      onDeleted={() => router.push('/roles')}
      onSaved={(role, action) => {
        if (action === 'quit') router.push('/roles');
        else if (action === 'addNew') router.push('/roles/new');
        else if (id === 'new') router.push(`/roles/${role.id}`);
      }}
      onUserClick={(user) => router.push(`/users/${user.id}`)}
      onAddUser={() => router.push('/users/new')}
      onPolicyClick={(policy) => router.push(`/policies/${policy.id}`)}
      onRoleClick={(role) => router.push(`/roles/${role.id}`)}
    />
  );
}
