/**
 * Workflow Detail Page
 *
 * Create/edit a workflow definition: name, description, and the state
 * machine drawn as a diagram (states, commands, policies, actions). Use the
 * `/workflows/new` route to create.
 *
 * The editor does not navigate. After a create it goes on as the editor of
 * the definition that was stored, and this page leaves for the list; after
 * an update it stays on the editor.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { WorkflowDetail } from '@/components/ui/workflow-management';

export default function WorkflowDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useLocaleRouter();

  return (
    <WorkflowDetail
      id={id}
      onBack={() => router.push('/workflows')}
      onSaved={() => {
        if (id === 'new') router.push('/workflows');
      }}
    />
  );
}
