/**
 * Workflow Assignment Detail Page
 *
 * Create/edit a workflow assignment: the workflow, the collection it runs
 * on, and the optional filter rule. Use the `/workflow-assignments/new`
 * route to create.
 *
 * The form does not navigate. After a create it goes on as the form of the
 * assignment that was stored. This page returns to the list after every
 * save.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { WorkflowAssignmentDetail } from '@/components/ui/workflow-management';

export default function WorkflowAssignmentDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useLocaleRouter();

  return (
    <WorkflowAssignmentDetail
      id={id}
      onBack={() => router.push('/workflow-assignments')}
      onSaved={() => router.push('/workflow-assignments')}
    />
  );
}
