/**
 * Fill Out Form Page
 *
 * Renders a saved form definition as a live create form via <DynamicForm/>.
 * Submitting creates a real item in the form's target collection.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { use } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Anchor, Box, Breadcrumbs, Stack, Text } from '@mantine/core';
import { DynamicForm } from '@/components/ui/form-builder';

export default function FillFormPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();

  return (
    <Box maw={720} mx="auto">
      <Stack gap="md">
        <Breadcrumbs>
          <Anchor component={Link} href="/forms" size="sm">
            Forms
          </Anchor>
          <Text size="sm">Fill out</Text>
        </Breadcrumbs>
        <DynamicForm
          definitionId={id}
          onSuccess={() => router.push('/forms')}
          onCancel={() => router.push('/forms')}
        />
      </Stack>
    </Box>
  );
}
