/**
 * Fill Form Screen Page
 *
 * Renders a saved form definition as a live create form via <DynamicForm/>.
 * Submitting creates a real item in the screen's target collection.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { use } from 'react';
import { useRouter } from 'next/navigation';
import { Box } from '@mantine/core';
import { DynamicForm } from '@/components/ui/form-builder';

export default function FillFormPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();

  return (
    <Box maw={720} mx="auto">
      <DynamicForm
        definitionId={id}
        onSuccess={() => router.push('/forms')}
        onCancel={() => router.push('/forms')}
      />
    </Box>
  );
}
