/**
 * Fill Out Form Page
 *
 * Renders a saved form definition as a live create form via <DynamicForm/>.
 * Submitting creates a real item in the form's target collection.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { use } from 'react';
import Link from 'next/link';
import { useLocaleHref, useLocaleRouter } from '@/lib/i18n/navigation';
import { useI18n } from '@/lib/i18n/provider';
import { Anchor, Box, Breadcrumbs, Stack, Text } from '@mantine/core';
import { DynamicForm } from '@/components/ui/form-builder';

export default function FillFormPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useLocaleRouter();
  const href = useLocaleHref();
  const { t } = useI18n();

  return (
    <Box maw={720} mx="auto">
      <Stack gap="md">
        <Breadcrumbs>
          <Anchor component={Link} href={href('/forms')} size="sm">
            {t('app.forms.title')}
          </Anchor>
          <Text size="sm">{t('app.forms.fillOut')}</Text>
        </Breadcrumbs>
        <DynamicForm
          definitionId={id}
          onSuccess={() => router.push('/forms')}
          onCancel={() => router.push('/forms')}
        />
      </Stack>
    </Box>
  );
}
