/**
 * Forms List Page
 *
 * Lists saved form definitions. Each row links to the builder (edit) and to
 * the fill-out page. If the definitions collection doesn't exist yet, a
 * prerequisite hint is shown instead of an error.
 *
 * Generated by @buildpad/cli
 */

'use client';

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  ActionIcon,
  Badge,
  Button,
  Card,
  Center,
  Group,
  Loader,
  Stack,
  Text,
  ThemeIcon,
  Title,
  Tooltip,
} from '@mantine/core';
import { IconEdit, IconForms, IconPlus } from '@tabler/icons-react';
import { FormsEmptyState, type FormDefinition } from '@/components/ui/form-builder';
import { useFormDefinitions } from '@/lib/buildpad/hooks';

export default function FormsListPage() {
  const router = useRouter();
  const { list } = useFormDefinitions();
  const [definitions, setDefinitions] = useState<FormDefinition[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    list()
      .then((defs) => !cancelled && setDefinitions(defs))
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load forms');
        }
      })
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (loading) {
    return (
      <Center mih={240}>
        <Loader />
      </Center>
    );
  }

  if (error) {
    return <FormsEmptyState error={error} />;
  }

  return (
    <Stack gap="md">
      <Group justify="space-between" align="flex-end">
        <div>
          <Title order={3}>Forms</Title>
          <Text size="sm" c="dimmed">
            Build forms and collect responses in your collections.
          </Text>
        </div>
        <Button
          leftSection={<IconPlus size={16} />}
          onClick={() => router.push('/forms/new')}
        >
          New form
        </Button>
      </Group>

      {definitions.length === 0 ? (
        <Center py={64}>
          <Stack gap="sm" align="center" maw={360}>
            <ThemeIcon size={48} radius="xl" variant="light">
              <IconForms size={26} />
            </ThemeIcon>
            <Text fw={600}>No forms yet</Text>
            <Text size="sm" c="dimmed" ta="center">
              Create your first form to start collecting responses.
            </Text>
            <Button
              leftSection={<IconPlus size={16} />}
              onClick={() => router.push('/forms/new')}
            >
              New form
            </Button>
          </Stack>
        </Center>
      ) : (
        <Stack gap="xs">
          {definitions.map((def) => (
            <Card key={def.id} withBorder padding="sm" radius="md">
              <Group justify="space-between" wrap="nowrap">
                <Group gap="sm" wrap="nowrap" style={{ minWidth: 0 }}>
                  <IconForms size={18} />
                  <div style={{ minWidth: 0 }}>
                    <Text fw={600} truncate>
                      {def.name}
                    </Text>
                    <Group gap={6}>
                      <Badge size="xs" variant="light" color="gray">
                        {def.target_collection}
                      </Badge>
                      {def.key && (
                        <Badge size="xs" variant="light" color="blue">
                          {def.key}
                        </Badge>
                      )}
                    </Group>
                  </div>
                </Group>
                <Group gap="xs" wrap="nowrap">
                  <Button
                    size="xs"
                    variant="light"
                    onClick={() => router.push(`/forms/${def.id}/fill`)}
                  >
                    Fill out
                  </Button>
                  <Tooltip label="Edit form">
                    <ActionIcon
                      variant="subtle"
                      onClick={() => router.push(`/forms/${def.id}`)}
                      aria-label="Edit form"
                    >
                      <IconEdit size={16} />
                    </ActionIcon>
                  </Tooltip>
                </Group>
              </Group>
            </Card>
          ))}
        </Stack>
      )}
    </Stack>
  );
}
