/**
 * The generated components barrel (components/ui/index.ts).
 *
 * `add` regenerates it after every install: one `export * from './<entry>'`
 * per installed component. Kept pure (the caller supplies file reads) so the
 * registry corpus tests can render exactly what a consumer gets without
 * touching the filesystem.
 */

import path from 'node:path';
import type { Registry } from '../resolver.js';

/** Read a file under components/ui/ (posix path relative to it); undefined when absent. */
export type ComponentsDirReader = (relPath: string) => string | undefined;

export interface ComponentsIndexResult {
  /** The file content to write to components/ui/index.ts. */
  content: string;
  /** Names more than one exported path provides, with every path in barrel order. */
  duplicates: Array<{ name: string; paths: string[] }>;
  /** Flat components exported through their SSR-safe wrapper instead. */
  skippedForWrapper: string[];
}

/** Components with known SSR issues that should be exported through a wrapper. */
const SSR_UNSAFE_COMPONENTS: Record<string, string> = {
  'input-block-editor': 'input-block-editor-wrapper',
};

const HEADER = [
  '/**',
  ' * Buildpad UI Components Index',
  ' * ',
  ' * Auto-generated by Buildpad CLI.',
  ' * Re-run "buildpad add" to update after adding new components.',
  ' */',
  '',
];

const MODULE_EXTENSIONS = ['.tsx', '.ts', '.jsx', '.js'];

/** Resolve a module path (no extension) under components/ui/ to an existing file. */
function resolveModule(modulePath: string, read: ComponentsDirReader): string | undefined {
  const base = path.posix.normalize(modulePath);
  for (const candidate of [
    ...MODULE_EXTENSIONS.map(ext => base + ext),
    ...MODULE_EXTENSIONS.map(ext => `${base}/index${ext}`),
  ]) {
    if (read(candidate) !== undefined) return candidate;
  }
  return undefined;
}

function stripComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"`])\/\/.*$/gm, '$1');
}

export interface ExportInfo {
  /** Exported only as a type (needs `export type` when re-exported). */
  typeOnly: boolean;
  /** Where the binding is declared (`file#name`), so re-exports of one declaration are not duplicates. */
  origin: string;
}

interface ExportScanContext {
  read: ComponentsDirReader;
  componentsAlias: string;
  cache: Map<string, Map<string, ExportInfo>>;
  inProgress: Set<string>;
}

/** Map a specifier to a file under components/ui/, or undefined (npm package, lib, …). */
function resolveSpecifier(spec: string, fromFile: string, ctx: ExportScanContext): string | undefined {
  if (spec.startsWith('.')) return resolveModule(path.posix.join(path.posix.dirname(fromFile), spec), ctx.read);
  // The generated barrel itself is never a source of declarations.
  if (spec === ctx.componentsAlias) return undefined;
  if (spec.startsWith(`${ctx.componentsAlias}/`)) {
    return resolveModule(spec.slice(ctx.componentsAlias.length + 1), ctx.read);
  }
  return undefined;
}

function originThrough(spec: string, name: string, fromFile: string, ctx: ExportScanContext): string {
  const file = resolveSpecifier(spec, fromFile, ctx);
  if (!file) return `${spec}#${name}`;
  return scanExports(file, ctx).get(name)?.origin ?? `${file}#${name}`;
}

/** Split `a, type b as c, default as d` into [local/imported name, exported/bound name, type-only]. */
function specifierList(list: string): Array<{ from: string; as: string; typeOnly: boolean }> {
  const out: Array<{ from: string; as: string; typeOnly: boolean }> = [];
  for (const element of list.split(',')) {
    const parts = element.trim().split(/\s+/).filter(Boolean);
    if (parts.length === 0) continue;
    const typeOnly = parts[0] === 'type' && parts.length > 1 && parts[1] !== 'as';
    const words = typeOnly ? parts.slice(1) : parts;
    out.push({ from: words[0], as: words.length >= 3 && words[1] === 'as' ? words[2] : words[0], typeOnly });
  }
  return out;
}

function scanExports(file: string, ctx: ExportScanContext): Map<string, ExportInfo> {
  const cached = ctx.cache.get(file);
  if (cached) return cached;
  const names = new Map<string, ExportInfo>();
  if (ctx.inProgress.has(file)) return names;
  ctx.inProgress.add(file);
  const raw = ctx.read(file);
  const source = raw === undefined ? '' : stripComments(raw);

  const add = (name: string, info: ExportInfo) => {
    // A name that is both a value and a type is re-exported as a value.
    const prior = names.get(name);
    names.set(name, prior ? { ...prior, typeOnly: prior.typeOnly && info.typeOnly } : info);
  };

  // Local bindings: declarations and imports (for `export { x }` without `from`).
  const localTypes = new Set<string>();
  for (const m of source.matchAll(/(?:^|[\s;])(?:export\s+)?(?:declare\s+)?(?:interface|type)\s+([A-Za-z_$][\w$]*)/g)) {
    localTypes.add(m[1]);
  }
  const imported = new Map<string, { spec: string; name: string; typeOnly: boolean }>();
  for (const m of source.matchAll(/\bimport\s+(type\s+)?(?:[A-Za-z_$][\w$]*\s*,\s*)?\{([^}]*)\}\s*from\s*['"]([^'"]+)['"]/g)) {
    for (const s of specifierList(m[2])) imported.set(s.as, { spec: m[3], name: s.from, typeOnly: !!m[1] || s.typeOnly });
  }

  for (const m of source.matchAll(
    /\bexport\s+(?:declare\s+)?(default\s+)?(?:async\s+)?(?:abstract\s+)?(?:const\s+enum|const|let|var|function\*?|class|enum)\s+([A-Za-z_$][\w$]*)/g,
  )) {
    if (m[1]) continue; // `export *` does not re-export the default
    add(m[2], { typeOnly: false, origin: `${file}#${m[2]}` });
  }
  for (const m of source.matchAll(/\bexport\s+(?:declare\s+)?(?:interface|type)\s+([A-Za-z_$][\w$]*)/g)) {
    add(m[1], { typeOnly: true, origin: `${file}#${m[1]}` });
  }
  for (const m of source.matchAll(/\bexport\s+(type\s+)?\{([^}]*)\}(?:\s*from\s*['"]([^'"]+)['"])?/g)) {
    const clauseTypeOnly = !!m[1];
    const fromSpec = m[3];
    for (const s of specifierList(m[2])) {
      if (s.as === 'default') continue;
      if (fromSpec) {
        add(s.as, { typeOnly: clauseTypeOnly || s.typeOnly, origin: originThrough(fromSpec, s.from, file, ctx) });
        continue;
      }
      const viaImport = imported.get(s.from);
      add(s.as, {
        typeOnly: clauseTypeOnly || s.typeOnly || (viaImport ? viaImport.typeOnly : localTypes.has(s.from)),
        origin: viaImport ? originThrough(viaImport.spec, viaImport.name, file, ctx) : `${file}#${s.from}`,
      });
    }
  }
  for (const m of source.matchAll(/\bexport\s*\*\s*as\s+([A-Za-z_$][\w$]*)\s*from/g)) {
    add(m[1], { typeOnly: false, origin: `${file}#${m[1]}` });
  }
  for (const m of source.matchAll(/\bexport\s*\*\s*from\s*['"]([^'"]+)['"]/g)) {
    const target = resolveSpecifier(m[1], file, ctx);
    if (!target) continue;
    for (const [name, info] of scanExports(target, ctx)) add(name, info);
  }

  ctx.inProgress.delete(file);
  ctx.cache.set(file, names);
  return names;
}

/**
 * Names a module under components/ui/ exports, with whether each is type-only
 * and where it is declared. Follows `export *` and re-exports within
 * components/ui/ (relative or through the components alias). A lexical
 * approximation, sufficient for the shipped sources: declarations,
 * `export { … }` lists (with `type` modifiers), imports re-exported by name and
 * star re-exports. `export default` is ignored because `export *` skips it.
 */
export function collectExportedNames(
  file: string,
  read: ComponentsDirReader,
  componentsAlias = '@/components/ui',
): Map<string, ExportInfo> {
  return scanExports(file, { read, componentsAlias, cache: new Map(), inProgress: new Set() });
}

/**
 * Render components/ui/index.ts for the installed components.
 *
 * A name provided by two exported modules is ambiguous under `export *` — the
 * barrel then fails to compile (TS2308) and the name resolves to nothing at
 * runtime. Each such name is re-exported explicitly from the first module (in
 * barrel order) that provides it; the others stay reachable through their own
 * path, e.g. `@/components/ui/users-management`.
 */
export function renderComponentsIndex(
  installedComponents: string[],
  registry: Pick<Registry, 'components'>,
  read: ComponentsDirReader,
  componentsAlias = '@/components/ui',
): ComponentsIndexResult {
  const exportLines = [...HEADER];
  const exportedPaths: string[] = [];
  const skippedForWrapper: string[] = [];

  const sorted = [...installedComponents].sort((a, b) => a.localeCompare(b));
  for (const componentName of sorted) {
    const component = registry.components.find(c => c.name === componentName);
    const mainFile = component?.files[0];
    if (!mainFile) continue;

    // Foldered components (vform/VForm.tsx, users-management/users-manager.tsx)
    // ship their own index barrel — export the folder. Flat ones export the file.
    const relToComponents = mainFile.target.replace(/^components\/ui\//, '');
    const folderName = relToComponents.includes('/') ? relToComponents.split('/')[0] : null;
    let exportPath: string;
    if (folderName) {
      exportPath = `./${folderName}`;
    } else {
      const fileName = path.posix.basename(mainFile.target, path.posix.extname(mainFile.target));
      const wrapper = SSR_UNSAFE_COMPONENTS[fileName];
      if (wrapper && read(`${wrapper}.tsx`) !== undefined) {
        exportPath = `./${wrapper}`;
        skippedForWrapper.push(fileName);
      } else {
        exportPath = `./${fileName}`;
      }
    }

    if (!exportedPaths.includes(exportPath)) {
      exportedPaths.push(exportPath);
      exportLines.push(`export * from '${exportPath}';`);
    }
  }

  // Which exported paths provide each name, and from which declaration. Two
  // paths re-exporting ONE declaration are not ambiguous; two declarations are.
  const ctx: ExportScanContext = { read, componentsAlias, cache: new Map(), inProgress: new Set() };
  const providers = new Map<string, Array<{ path: string } & ExportInfo>>();
  for (const exportPath of exportedPaths) {
    const file = resolveModule(exportPath.slice(2), read);
    if (!file) continue;
    for (const [name, info] of scanExports(file, ctx)) {
      providers.set(name, [...(providers.get(name) ?? []), { path: exportPath, ...info }]);
    }
  }
  const duplicates = [...providers.entries()]
    .filter(([, list]) => new Set(list.map(p => p.origin)).size > 1)
    .map(([name, list]) => ({ name, paths: list.map(p => p.path), first: list[0] }));

  if (duplicates.length > 0) {
    exportLines.push(
      '',
      '// Exported by more than one component: ambiguous under `export *` (TS2308),',
      '// so each is re-exported from the first one. Import the others by path.',
    );
    for (const d of duplicates) {
      const keyword = d.first.typeOnly ? 'export type' : 'export';
      exportLines.push(`${keyword} { ${d.name} } from '${d.first.path}';`);
    }
  }

  return {
    content: exportLines.join('\n') + '\n',
    duplicates: duplicates.map(({ name, paths }) => ({ name, paths })),
    skippedForWrapper,
  };
}
