/**
 * Policies List Page
 *
 * Policies administration surface: search, user/role attachment counts,
 * pagination, and permission-gated create/edit/delete.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useRouter } from 'next/navigation';
import { PoliciesManager } from '@/components/ui/users-management';

export default function PoliciesPage() {
  const router = useRouter();

  return (
    <PoliciesManager
      onPolicyClick={(policy) => router.push(`/policies/${policy.id}`)}
      onCreatePolicy={() => router.push('/policies/new')}
    />
  );
}
