/**
 * Roles List Page
 *
 * Roles administration surface: search, member counts, pagination, and
 * permission-gated create/edit/delete.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useRouter } from 'next/navigation';
import { RolesManager } from '@/components/ui/users-management';

export default function RolesPage() {
  const router = useRouter();

  return (
    <RolesManager
      onRoleClick={(role) => router.push(`/roles/${role.id}`)}
      onCreateRole={() => router.push('/roles/new')}
    />
  );
}
