/**
 * User Detail Page
 *
 * Create/edit a user: profile fields, role assignment (M2M), status,
 * static API token, and direct policy attachment. Use the `/users/new`
 * route to create.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useRouter } from 'next/navigation';
import { UserDetail } from '@/components/ui/users-management';

export default function UserDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();

  return (
    <UserDetail
      id={id}
      onBack={() => router.push('/users')}
      onDeleted={() => router.push('/users')}
      onSaved={() => router.push('/users')}
      onPolicyClick={(policy) => router.push(`/policies/${policy.id}`)}
    />
  );
}
