/**
 * Workflows List Page
 *
 * Workflow definitions: search, pagination, and permission-gated
 * create/edit/delete. A row opens the definition editor.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { useLocaleRouter } from '@/lib/i18n/navigation';
import { WorkflowsManager } from '@/components/ui/workflow-management';

export default function WorkflowsPage() {
  const router = useLocaleRouter();

  return (
    <WorkflowsManager
      onWorkflowClick={(workflow) => router.push(`/workflows/${workflow.id}`)}
      onCreateWorkflow={() => router.push('/workflows/new')}
    />
  );
}
