/**
 * The generated components barrel (components/ui/index.ts).
 */

import { describe, expect, test } from 'vitest';
import { collectExportedNames, renderComponentsIndex } from '../src/utils/components-index.js';
import type { ComponentEntry, Registry } from '../src/resolver.js';

function component(name: string, target: string): ComponentEntry {
  return {
    name,
    title: name,
    description: '',
    category: 'x',
    files: [{ source: `x/${name}`, target }],
    dependencies: [],
    internalDependencies: [],
  };
}

const registry = {
  components: [
    component('input', 'components/ui/input.tsx'),
    component('file-manager', 'components/ui/file-manager/file-manager.tsx'),
    component('users-management', 'components/ui/users-management/users-manager.tsx'),
    component('select-icon', 'components/ui/select-icon.tsx'),
    component('map', 'components/ui/map.tsx'),
    component('map-with-real-map', 'components/ui/map-with-real-map.tsx'),
  ],
} as unknown as Registry;

function reader(files: Record<string, string>) {
  return (rel: string) => files[rel];
}

// Byte-for-byte the header the barrel has always had (note the ' * ' line).
const HEADER = [
  '/**',
  ' * Buildpad UI Components Index',
  ' * ',
  ' * Auto-generated by Buildpad CLI.',
  ' * Re-run "buildpad add" to update after adding new components.',
  ' */',
  '',
].join('\n');

describe('renderComponentsIndex', () => {
  test('without duplicates the barrel is the plain export * list (unchanged format)', () => {
    const { content, duplicates } = renderComponentsIndex(
      ['input', 'file-manager'],
      registry,
      reader({
        'input.tsx': 'export const Input = () => null;',
        'file-manager/index.tsx': "export { FileManager } from './file-manager';",
        'file-manager/file-manager.tsx': 'export function FileManager() {}',
      }),
    );
    expect(duplicates).toEqual([]);
    expect(content).toBe(`${HEADER}\nexport * from './file-manager';\nexport * from './input';\n`);
  });

  test('a name declared by two components is re-exported from the first (TS2308)', () => {
    const { content, duplicates } = renderComponentsIndex(
      ['users-management', 'file-manager'],
      registry,
      reader({
        'file-manager/index.tsx':
          "export { DeleteConfirmModal } from './delete-confirm-modal';\nexport type { DeleteConfirmModalProps } from './delete-confirm-modal';",
        'file-manager/delete-confirm-modal.tsx':
          'export interface DeleteConfirmModalProps { count: number }\nexport function DeleteConfirmModal() {}',
        'users-management/index.tsx':
          "export {\n  DeleteConfirmModal,\n  type DeleteConfirmModalProps,\n} from './delete-confirm-modal';",
        'users-management/delete-confirm-modal.tsx':
          'export type DeleteConfirmModalProps = { opened: boolean };\nexport const DeleteConfirmModal = () => null;',
      }),
    );
    expect(duplicates).toEqual([
      { name: 'DeleteConfirmModal', paths: ['./file-manager', './users-management'] },
      { name: 'DeleteConfirmModalProps', paths: ['./file-manager', './users-management'] },
    ]);
    expect(content).toContain("export * from './file-manager';\nexport * from './users-management';\n");
    expect(content).toContain("export { DeleteConfirmModal } from './file-manager';\n");
    expect(content).toContain("export type { DeleteConfirmModalProps } from './file-manager';\n");
  });

  test('re-exports of ONE declaration are not duplicates', () => {
    const { duplicates } = renderComponentsIndex(
      ['select-icon', 'users-management', 'map', 'map-with-real-map'],
      registry,
      reader({
        'select-icon.tsx': 'export const IconDisplay = () => null;',
        'users-management/index.tsx': "export { IconDisplay } from '@/components/ui/select-icon';",
        'map.tsx': 'export type GeometryType = string;\nexport function Map() {}',
        'map-with-real-map.tsx':
          "import type { GeometryType } from './map';\nexport type { GeometryType };\nexport function MapWithRealMap() {}",
      }),
    );
    expect(duplicates).toEqual([]);
  });
});

describe('collectExportedNames', () => {
  test('declarations, lists, aliases, type modifiers and export *', () => {
    const names = collectExportedNames(
      'a.tsx',
      reader({
        'a.tsx': [
          '// export const Commented = 1;',
          'export const A = 1;',
          'export default function Hidden() {}',
          'export interface Props {}',
          'type Local = string;',
          'const local = 1;',
          'export { local as renamed, type Local as LocalAlias };',
          "export * from './b';",
          "export * as ns from './b';",
        ].join('\n'),
        'b.ts': 'export enum E { X }\nexport type T = 1;',
      }),
    );
    expect(Object.fromEntries([...names].map(([k, v]) => [k, v.typeOnly]))).toEqual({
      A: false,
      Props: true,
      renamed: false,
      LocalAlias: true,
      E: false,
      T: true,
      ns: false,
    });
  });
});
